apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata: 
    name: springboot-app-pod
spec:
   scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: springboot-app-deployment
   minReplicas: 1
   maxReplicas: 5
   metrics:
     - type: Resource
       resource:
         name: cpu
         targetAverageUtilization: 3
