apiVersion: v1
kind: Pod
metadata:
    name: springboot-app-pod
    labels:
       name: springboot-app-pod
       app: demo-springboot-app
spec:
  containers:
    - name: springboot-app
      image: pandurangan/springboot-app:v1
      ports:
        - containerPort: 8080
