apiVersion: v1
kind: Service
metadata:
    name: springboot-service
    labels:
       name: springboot-service
       app: demo-springboot-app
spec:
   type: LoadBalancer
   ports:
      - port: 8080
        targetPort: 8080
   selector:
      name: springboot-app-pod
      app: demo-springboot-app

